### ISSUE TITLE
Using Client, method on

### ISSUE THREAD

**Issue by michelpf** [TelegramBot/DevAnswerBot#1]
Your API is awesome, congratulations! I just need more examples to explore its entire potential. For example, the method "on" seems to be very promising and time saver when we have to deal with interaction. Otherwise, its usage is a little complex. Digging and testing, I figure out how to check simple verifications using the second parameter. The first I have no ideal what it is for. Check my example:

$bot->on(function ($message) use ($bot) {

```
     $bot->sendMessage($message->getChat()->getId(), '?!');

},function ($message) use ($bot) {
     if ($message->getText()=="b"){
     $bot->sendMessage($message->getChat()->getId(), 'OK!');
     }
     else
     {

     $bot->sendMessage($message->getChat()->getId(), 'Incorrect!');
     }
});
```

When is send the word b, triggers the OK message, else, Incorrect message. But all the actions were set up on the second parameter. 
Can you give me a simple example to check if the message was sent, example, a registration process. First /register then the Bot asks for e-mail, then the bot validates it, if OK confirms, if it's not, ask again.

**Comment by iGusev** [comment]
My bad. Mistake in docs. If second closure will return true (or if you are passed null instead of closure), first one will be executed.

For example, we can realize `ping`:

``` php
$bot->on(function (Message $message) use ($bot) {
    $bot->sendMessage($message->getChat()->getId(), 'pong!');
}, function (Message $message) {
    return $message->getText() == 'ping';
});
```

You can realize your example via two events:

``` php
$bot->on(function (Message $message) use ($bot) {
    $bot->sendMessage($message->getChat()->getId(), 'OK!');
}, function (Message $message) {
    return $message->getText() == 'b';
});
$bot->on(function (Message $message) use ($bot) {
    $bot->sendMessage($message->getChat()->getId(), 'Incorrect!');
}, function (Message $message) {
    return $message->getText() != 'b';
});
```

Or you can ignore checker and handling all messages in your closure:

``` php
$bot->on(function (Message $message) use ($bot) {
    if ($message->getText() == 'b') {
        $bot->sendMessage($message->getChat()->getId(), 'OK!');
    } else {
        $bot->sendMessage($message->getChat()->getId(), 'Incorrect!');
    }
});
```

But I recommend using commands (messages beginning with "/"). If user sends `/b`, bot replies `OK!`:

``` php
$bot->command('b', function ($message) use ($bot) {
    $bot->sendMessage($message->getChat()->getId(), 'OK!');
});
```

Also, command can be used with the passed parameters:

``` php
$bot->command('register', function ($message, $mail) use ($bot) {
    $bot->sendMessage($message->getChat()->getId(), $mail);
});
```

If user sends `/register mail@igusev.ru`, bot replies `mail@igusev.ru`. 

`command` implemented via `on`:

``` php
public function command($name, Closure $action)
{
    return $this->on(self::getEvent($action), self::getChecker($name));
}
```

``` php
public function command($name, Closure $action)
{
    return $this->on(function (Message $message) use ($action) {
        preg_match('/^\/([^\s@]+)(@\S+)?\s?(.*)$/', $message->getText(), $matches);

        if (isset($matches[3]) && !empty($matches[3])) {
            $parameters = str_getcsv($matches[3], chr(32));
        } else {
            $parameters = [];
        }

        array_unshift($parameters, $message);

        $action = new ReflectionFunction($action);

        if (count($parameters) >= $action->getNumberOfRequiredParameters()) {
            $action->invokeArgs($parameters);
        }

        return false;
    }, function (Message $message) use ($name) {
        if (!strlen($message->getText())) {
            return false;
        }

        preg_match('/^\/([^\s@]+)(@\S+)?\s?(.*)$/', $message->getText(), $matches);

        return !empty($matches) && $matches[1] == $name;
    });
}
```

**Comment by michelpf** [comment]
I know how difficult is to maintain such system like that, no problem. I'm glad you can answer quickly to that questions.

For sure using your code at the right way is even better.

Thanks again for your clarification.

Just one note, your following code is not running:

$bot->on(function (Message $message) use ($bot) {
    $bot->sendMessage($message->getChat()->getId(), 'OK!');
}, function (Message $message) {
    return $message->getText() == 'b';
});
$bot->on(function (Message $message) use ($bot) {
    $bot->sendMessage($message->getChat()->getId(), 'Incorrect!');
}, function (Message $message) {
    return $message->getText() != 'b';
});

I put on that way, adding "use ($bot) " as the first parameter, and works fine.

$bot->on(function (Message $message) use ($bot) {
    $bot->sendMessage($message->getChat()->getId(), 'OK!');
}, function (Message $message) {
    return $message->getText() == 'b';
});
$bot->on(function (Message $message) use ($bot) {
    $bot->sendMessage($message->getChat()->getId(), 'Incorrect!');
}, function (Message $message) {
    return $message->getText() != 'b';
});
