### ISSUE TITLE
Как вывести меню пользователю?  

### ISSUE THREAD

**Issue by Zircool** [TelegramBot/DevAnswerBot#2]
На основании примера, пытаюсь вывести меню, не получается. 

$keyboard = new \TelegramBot\Api\Types\ReplyKeyboardMarkup(array(array("one", "two", "three")), true); // true for one-time keyboard

	$bot->command('key', function ($message) use ($bot) {
		$bot->sendMessage($message->getChat()->getId(),"Выберите пункт меню",null,false,null,$keyboard);
	});   

Что не так делаю?

**Comment by Zircool** [comment]
Разобрался, keyboard вызывал внутри функции, а определял вне.

**Comment by Zircool** [comment]
А есть пример, в зависимости от отправленного контента, его обработка?  К примеру отправил пользователь изображение, ты получил его ID и сохранил, голосовое сообщение - получил его ID и сохранил.

**Comment by iGusev** [comment]
Все есть внутри получаемого Message объекта

**Comment by iGusev** [comment]
https://github.com/TelegramBot/Api/blob/master/src/Types/Message.php
